apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-prometheus
  namespace: argocd
spec:
  project: default
  sources:
    # --- Source 1: The Upstream Helm Chart ---
    - repoURL: 'https://prometheus-community.github.io/helm-charts'
      chart: kube-prometheus-stack
      targetRevision: 69.x.x # Use the latest stable version
      helm:
        # Link to the values file in the second source (Git)
        valueFiles:
          - $values/monitoring/values.yaml
    
    # --- Source 2: Your Private Git Repository ---
    - repoURL: https://github.com/mike-palacio-nice/kubernetes-deployment.git
      targetRevision: HEAD
      ref: values # This creates the '$values' alias used above
  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true # Mandatory for large Prometheus CRDs